[package]
name = "pwwr"
version = "0.1.0"
authors = ["meganehouser <sleepy.st818@gmail.com>"]

[dependencies]
rust-crypto = "^0.2"
clap = "2"
rand = "0.3"
rpassword="0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.11"
